# Generated by Django 4.2.7 on 2026-01-09 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('marked_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distance_from_center', models.FloatField(help_text='Distance in meters from session location')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance_sessions.attendancesession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-marked_at'],
                'indexes': [models.Index(fields=['session', 'student'], name='attendance__session_e37d63_idx'), models.Index(fields=['marked_at'], name='attendance__marked__4ce7ce_idx')],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
